apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ksqldb
  namespace: ksqldb
  includeCRDs: true
  releaseName: ksqldb
  version: 0.3.0
  repo: https://licenseware.github.io/charts/
  valuesInline:
    kafka:
      create: false
    configMapPairs:
      KSQL_BOOTSTRAP_SERVERS: kafka-cluster-kafka-brokers:9092