apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: cni
  namespace: kube-system
  includeCRDs: true
  releaseName: istio-cni
  version: 1.15.3
  repo: https://istio-release.storage.googleapis.com/charts
  valuesInline:
    defaultRevision: 1-15-3