apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: confluent-schema-registry
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: plain
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: registry-schemas
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        type: allow
      - resource:
          type: group
          name: schema-registry
          patternType: prefix
        operations:
          - Create
          - Describe
          - Write
        type: allow
      - resource:
          type: topic
          name: __consumer_offsets
          patternType: literal
        operations:
          - Describe
        type: allow