apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: istiod
  namespace: istio-system
  includeCRDs: true
  releaseName: istio-istiod
  version: 1.16.1
  repo: https://istio-release.storage.googleapis.com/charts