apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-agent-operator
helmCharts:
- name: grafana-agent-operator
  namespace: grafana-agent-operator
  includeCRDs: true
  releaseName: grafana-agent-operator
  version: 0.2.4
  repo: https://grafana.github.io/helm-charts