apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: metrics-server
  namespace: kube-system
  includeCRDs: true
  releaseName: metrics-server
  version: 3.8.3
  repo: https://kubernetes-sigs.github.io/metrics-server/
  valuesInline:
    apiService:
      insecureSkipTLSVerify: true
