apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: external-secrets
  namespace: external-secrets
  includeCRDs: true
  releaseName: external-secrets
  version: 0.5.8
  repo: https://charts.external-secrets.io