apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: external-dns
  namespace: external-dns
  includeCRDs: true
  releaseName: external-dns
  version: 1.12.0
  repo: https://kubernetes-sigs.github.io/external-dns/
  valuesInline:
    registry: txt
    txtOwnerId: "k8s"
    txtPrefix: "external-dns-"
    provider: rfc2136
    domainFilters:
      - k8s.templarfelix.com
    sources:
      - service
      - ingress
    extraArgs:
      - --rfc2136-host=172.16.226.10
      - --rfc2136-port=53
      - --rfc2136-zone=k8s.templarfelix.com
      - --rfc2136-tsig-secret=G0+3iQ+b12VaRzHvAPvvFw3KMoLbC5k8vu70kF6cV6Q=
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-keyname=externaldns-key
      - --rfc2136-tsig-axfr